# Generated by Django 3.0.1 on 2019-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('store_tel', models.CharField(max_length=20)),
                ('store_address', models.CharField(max_length=20)),
                ('store_district', models.CharField(max_length=10)),
            ],
        ),
    ]
