# Generated by Django 3.0.1 on 2019-12-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
