# Generated by Django 3.0.1 on 2019-12-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shoe_size',
        ),
    ]
