# Generated by Django 3.0.1 on 2019-12-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_company_inventory_product_storage_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='warehouse_id',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
