# Generated by Django 3.0.1 on 2019-12-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20191221_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
        ),
    ]
