# Generated by Django 3.0.1 on 2019-12-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_inventory_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='shoe_size',
            field=models.CharField(default='23', max_length=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='shoe_size',
            field=models.CharField(default='23', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product_id', 'store_id', 'shoe_size')},
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('product_id', 'warehouse_id', 'shoe_size')},
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('purchase_method', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
            options={
                'unique_together': {('product_id', 'customer_id')},
            },
        ),
    ]
