# Generated by Django 3.0.1 on 2019-12-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191221_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Inventory'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shoe_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='shoe_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=set(),
        ),
    ]
