# Generated by Django 3.0.1 on 2019-12-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191221_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product_id', 'store_id', 'shoe_size')},
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('product_id', 'warehouse_id', 'shoe_size')},
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
