# Generated by Django 3.0.1 on 2019-12-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191221_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('purchase_method', models.CharField(max_length=20)),
                ('shoe_size', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
            ],
            options={
                'unique_together': {('product_id', 'customer_id', 'shoe_size')},
            },
        ),
    ]
