# Generated by Django 3.0.1 on 2019-12-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_purchase_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Inventory'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateField(),
        ),
    ]
