# Generated by Django 3.0.1 on 2019-12-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_purchase_purchase_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storage',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='warehouse_id',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
