# Generated by Django 3.0.1 on 2019-12-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191226_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_cost', models.DecimalField(decimal_places=0, max_digits=20)),
                ('product_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
            ],
        ),
    ]
