# Generated by Django 3.0.1 on 2019-12-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_customer_customer_satisfication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_satisfication',
            field=models.CharField(max_length=10),
        ),
    ]
