# Generated by Django 3.0.1 on 2019-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191226_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('warehouse_address', models.CharField(max_length=20)),
            ],
        ),
    ]
