# Generated by Django 3.0.1 on 2019-12-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.CharField(max_length=20)),
                ('inventory_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
            options={
                'unique_together': {('product_id', 'store_id', 'shoe_size')},
            },
        ),
    ]
