# Generated by Django 3.0.1 on 2019-12-26 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.CharField(max_length=20)),
                ('storage_quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Warehouse')),
            ],
            options={
                'unique_together': {('product_id', 'warehouse_id', 'shoe_size')},
            },
        ),
    ]
