# Generated by Django 3.0.1 on 2019-12-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_method', models.CharField(max_length=20)),
                ('discount_rate', models.DecimalField(decimal_places=0, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product')),
                ('shoe_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Inventory')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Store')),
            ],
            options={
                'unique_together': {('product_id', 'shoe_size')},
            },
        ),
    ]
