# Generated by Django 3.0.1 on 2019-12-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order'),
        ('home', '0013_auto_20191228_2057'),
    ]

    operations = [
    ]
